### ISSUE TITLE
Vacuum state stops updating until Home Assistant restart

### ISSUE THREAD

**Issue by rothnic** [DeebotUniverse/Deebot-4-Home-Assistant#109]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I was working on an automation that vacuums a couple custom areas (rugs). At the start of the automation, it checks the mop status and if it is installed it warns the user about the mop through google assistant and doesn't start the vacuuming routine.

When testing, I confirmed it worked as expected with the mop installed. I then tried removing the mop and running the automation again and it was still recognized as installed. Next, I tested a service call to update the Water status like this:

```
service: deebot.refresh
data:
  part: Water
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
```

When the vacuum is docked, refreshing the Water status does not update the mop install state. I'm not sure if this is a bug or an inherent limitation of the api.

### On which deebot vacuum you have the issue?

DEEBOT OZMO T8+

### Which version of the Deebot component are you using?

1.1.2

### Which version of Home Assistant are you using?

2021.12.8

### What type of installation are you running?

Home Assistant Container

### Country

us

### Continent

na

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
I didn't see any errors or warnings. I would have to gather debug logs if needed.
```

### Additional information

If this isn't possible due to API limitations, feel free to close. Thought it would be worth mentioning at least.

**Comment by edenhaus** [comment]
On my deebot 950, the vacuum sends immediately out an event, when I connect the mop, but not when I disconnect it.
You can try to actiavte debug logs and check if maybe your newer model send out an event, which is not handled yet and also check what you get back from [`getWaterLevel`](https://deebot.readthedocs.io/advanced/data_types/json/commands/water/).
If you get back `enable=true` even when the mop is disconnected, then I cannot do nothing unfortunately.

**Comment by rothnic** [comment]
Thanks for the guidance. I setup a quick script using deebot-client to get the water level directly. I just need to wait for the vacuum to get done mopping to do some testing on it when at the dock, then I'll get back to you.

**Comment by rothnic** [comment]
So, I was able to see the event from the vacuum after docking it with the mop, then removing the mop. I am also seeing the state reflected in home assistant now. So, I'm not sure what was happening before that caused the state to not update.

```
DEBUG:deebot_client.mqtt_client:Got message: topic=iot/atr/onWaterInfo/XXXXXXXX; payload={"header":{"pri":1,"tzm":480,"ts":"1644419131635","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"data":{"enable":0,"amount":4,"type":0,"sweepType":1}}};
DEBUG:deebot_client.vacuum_bot:Handle message onWaterInfo: {'header': {'pri': 1, 'tzm': 480, 'ts': '1644419131635', 'ver': '0.0.1', 'fwVer': '1.7.1', 'hwVer': '0.1.1'}, 'body': {'data': {'enable': 0, 'amount': 4, 'type': 0, 'sweepType': 1}}}
DEBUG:deebot_client.vacuum_bot:Falling back to old handling way...
DEBUG:deebot_client.events.event_bus:Notify subscribers with WaterInfoEvent(mop_attached=False, amount=<WaterAmount.ULTRAHIGH: 4>)
```

**Comment by edenhaus** [comment]
Please watch it the next days, maybe there is a rare race condition, where the event is not received correctly

**Comment by rothnic** [comment]
Maybe this is a broader issue I'm having. It seems like sometimes the vacuum status gets lost. I tried using the deebot client library to check there and I just get nothing from it.

```
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:deebot_client._api_client:got {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:deebot_client.vacuum_bot:Handle command getCleanInfo: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
WARNING:deebot_client.commands.common:Command "getCleanInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:deebot_client._api_client:got {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:deebot_client.vacuum_bot:Handle command getWaterInfo: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
WARNING:deebot_client.commands.common:Command "getWaterInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:deebot_client._api_client:got {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:deebot_client.vacuum_bot:Handle command getWaterInfo: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
WARNING:deebot_client.commands.common:Command "getWaterInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.mqtt.handler:[CMD 0xd0] b''
DEBUG:gmqtt.mqtt.handler:[PONG REQUEST] 0xd0 b''
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
DEBUG:gmqtt.client:[QoS query IS EMPTY]
```

**Comment by rothnic** [comment]
Going to close this. I don't think it is specific to water level reporting and I've tested that it does at least work.

**Comment by edenhaus** [comment]
Strange that you get 500. If you find out something please open a issue, so maybe we can fix it or create a workaround 😊

**Comment by rothnic** [comment]
At this point I was having trouble getting the vacuum to do anything. I finally had to restart the vacuum to get it to respond again. But yeah, if I find anything more specific out I'll open another issue for it.

**Comment by rothnic** [comment]
I did end up finding some error logs in home assistant where the non-response might have been causing some unhandled exceptions.

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:12 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:12 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:14 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:19 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:29 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:07:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 748, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 766, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
image_bytes = await camera.async_camera_image(
File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
_draw_positions(self._map_data.positions, image, image_box)
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 103, in _draw_positions
_calc_point(position.x, position.y, image_box),
File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 91, in _calc_point
_calc_value(x, image_box[0], image_box[2]),
TypeError: 'NoneType' object is not subscriptable
2022-02-12 08:29:02 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 138, in _call_refresh_function
await self._execute_command(commands[0])
File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 115, in execute_command
result = command.handle_requested(self.events, response)
File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 37, in handle_requested
stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
```

**Comment by edenhaus** [comment]
To fix this errors I need debug logs, where all requests are logged. So I can detect this requests and handle them correctly

**Comment by rothnic** [comment]
@edenhaus I believe this issue might be related to what was brought up here: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/discussions/137. I'm going to go ahead and reopen it for visibility, but we do need to find more information about it. I'm just not sure how at this point to capture any logging around it since it happens unpredictably.

After some period of time of home assistant running, I have come across this issue where none of the states update. I encountered this issue again today where I was able to trigger the vacuum to start cleaning, but the state never changed to cleaning.

I discovered this issue because I have a script that triggers vacuuming a custom area, then it waits for the state to change to docked, then it starts vacuuming another custom area. When running this script it just seemed to skip right through it and it was because the state never changed.

After I restarted Home Assistant while the vacuum was cleaning, the state of the vacuum was updated to the correct state.

**Comment by edenhaus** [comment]
@rothnic Please open a new issue so we don't mix things like the error with `stopReason` and also the versions and co has changed.
As sending commands is working, but no state updates are received, there is something wrong with the mqtt connection. Normally a automatic reconnect should be triggered. It can also be that ecovacs changed something on the server side e.g. closing not correctly of long living connections as the app is only connected via mqtt a short time.

Or maybe it has nothing to do with a new HA version.
To correctly document this issue, a new issue with new config data and logs is better.
