### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by geofffarmer** [DeebotUniverse/Deebot-4-Home-Assistant#199]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Log contains this entry:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 20:11:14 (1 occurrences)
Last logged: 20:11:14

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 139, in _call_refresh_function
    await self._execute_command(commands[0])
  File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 111, in execute_command
    result = command.handle_requested(self.events, response)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 38, in handle_requested
    stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'

```

### Diagnostics information

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.45",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "alexa_media": {
      "version": "3.10.15",
      "requirements": [
        "alexapy==1.25.5",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "alarmo": {
      "version": "v1.9.4",
      "requirements": []
    },
    "hass_agent_notifier": {
      "version": "2022.3.15",
      "requirements": []
    },
    "hildebrandglow_dcc": {
      "version": "0.6.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "ical": {
      "version": "1.3",
      "requirements": [
        "icalendar==4.0.7"
      ]
    },
    "deebot": {
      "version": "1.3.1",
      "requirements": [
        "deebot-client==1.4.0",
        "numpy>=1.21.2"
      ]
    },
    "fullykiosk": {
      "version": "1.0.2",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "codeowners": [
      "@DeebotUniverse",
      "@edenhaus"
    ],
    "config_flow": true,
    "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
    "domain": "deebot",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues",
    "name": "Deebot 4 Home Assistant",
    "requirements": [
      "deebot-client==1.4.0",
      "numpy>=1.21.2"
    ],
    "version": "1.3.1",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "4d134b8275c1fcb9aa7f1cd4b31d4b0d",
      "version": 3,
      "domain": "deebot",
      "title": "Robot Vacuum",
      "data": {
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "country": "uk",
        "continent": "eu",
        "devices": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "device": {
      "did": "**REDACTED**",
      "name": "**REDACTED**",
      "class": "ty84oi",
      "resource": "iCmB",
      "nick": "Meryl Sweep",
      "company": "eco-ng",
      "bindTs": 1654167675702,
      "service": {
        "jmq": "jmq-ngiot-eu.dc.ww.ecouser.net",
        "mqs": "api-ngiot.dc-as.ww.ecouser.net"
      },
      "homeId": "62964ee90eb7ecabaec3975c",
      "homeSort": 1,
      "deviceName": "DEEBOT N8",
      "icon": "https://portal-ww.ecouser.net/api/pim/file/get/60627bcafc527c00087fdb0c",
      "ota": true,
      "UILogicId": "N8_PLUS",
      "materialNo": "110-2029-1201",
      "pid": "5fbcac79c7260e0008585c94",
      "product_category": "DEEBOT",
      "model": "N8_WHITE",
      "updateInfo": {
        "needUpdate": false,
        "changeLog": ""
      },
      "status": 1,
      "offmap": true
    }
  }
}
```

### Additional information

Other than the log entry I can't see anything that isn't functioning.

**Comment by edenhaus** [comment]
Can you please attach [debug logs](https://deebot.readthedocs.io/integrations/home-assistant/issues/).

**Comment by geofffarmer** [comment]
My log exploded to 34k lines!

I didn't want to go through all of it looking for anything confidential so I searched for the original error and tried to work out how much of the surrounding info is relevent. Is this sufficient? I've replaced some things with stars if I though they may be personal info.

```
2022-06-27 19:06:49 DEBUG (MainThread) [deebot_client._api_client] got {'ret': 'ok', 'logs': [{'ts': 1656265100, 'last': 139, 'area': 2, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656265049, 'last': 8, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264902, 'last': 103, 'area': 1, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264870, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264818, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264727, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264599, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264306, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264256, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264219, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264186, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264154, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264126, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264085, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656262848, 'last': 69, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 3, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655565082, 'last': 118, 'area': 2, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564615, 'last': 366, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564399, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564222, 'last': 73, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 3, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655467983, 'last': 2502, 'area': 33, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}]}
2022-06-27 19:06:49 DEBUG (MainThread) [deebot_client.vacuum_bot] Handle command GetCleanLogs: {'ret': 'ok', 'logs': [{'ts': 1656265100, 'last': 139, 'area': 2, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656265049, 'last': 8, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264902, 'last': 103, 'area': 1, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264870, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264818, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264727, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264599, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264306, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264256, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264219, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264186, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264154, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264126, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656264085, 'last': 0, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1656262848, 'last': 69, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 3, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655565082, 'last': 118, 'area': 2, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564615, 'last': 366, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564399, 'last': 61, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 2, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655564222, 'last': 73, 'area': 0, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 3, 'aiopen': 1, 'powerMopType': 1}, {'ts': 1655467983, 'last': 2502, 'area': 33, 'id': 'acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/acb2e78e-8f25-454a-a0ac-***@***@iCmB', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'stopReason': 1, 'aiopen': 1, 'powerMopType': 1}]}
2022-06-27 19:06:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 139, in _call_refresh_function
await self._execute_command(commands[0])
File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 111, in execute_command
result = command.handle_requested(self.events, response)
File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 38, in handle_requested
stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
2022-06-27 19:06:49 DEBUG (MainThread) [deebot_client._api_client] calling api iot/devmanager.do with {'cmdName': 'getTotalStats', 'payload': {'header': {'pri': '1', 'ts': 1656353209.452774, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'acb2e78e-8f25-454a-a0ac-db3a297ceebe', 'toRes': 'iCmB', 'toType': 'ty84oi'}
```

**Comment by geofffarmer** [comment]
And then, when I posted this, the starts got taken out.

**Comment by edenhaus** [comment]
Can you please verify with the ecovacs, which is different with the 17th clean log entry? Entry timestamp is `Sat Jun 18 2022 15:03:35 GMT+0000`
This entry is missing the key `stopReason` and I'm wondering why

**Comment by geofffarmer** [comment]
I'm struggling to remember what could have happened at that time. There was one occasion when I picked up the vacuum. Could it be this? What do the stopReasons 1, 2 and 3 mean?

Is there a way to delete this history - without deleting everything?

Thank you for your efforts on this.

**Comment by edenhaus** [comment]
Is the app showing the entry? Can you see there some differences between the other entries?

The meaning of StopRean can be found under https://github.com/DeebotUniverse/client.py/blob/7dbb40fb5953c2256bf78e2c2f3d030a38c0f845/deebot_client/events/__init__.py#L31

**Comment by geofffarmer** [comment]
The log looks like this:
![Screenshot_20220629-041139_ECOVACS HOME](https://user-images.githubusercontent.com/29042424/176343985-22978c8d-678f-454d-89fb-cea5b9a20eed.jpg)
I think the entry causing the problem is this one:
![Screenshot_20220629-041259_ECOVACS HOME](https://user-images.githubusercontent.com/29042424/176344391-0f236a07-5d73-413a-80a1-0d9b701f3611.jpg)
However, I found my timezone was set to GMT+8 but this doesn't tie in with any log entries.

Will the rouge entry drop off the log eventually?

**Comment by geofffarmer** [comment]
It may be with noting that this is soon after the vacuum got very confused about where it was in my home. If you look at the map you can see that there is a kind of partial duplicate image shifted downwards. This has since corrected itself.

**Comment by edenhaus** [comment]
It’s fine, i was only wondering.
I don’t know how many entries ecovacs stores itself.

With the new update coming next week, the sensor should work again.

**Comment by geofffarmer** [comment]
Thank you for looking at this
