### ISSUE TITLE
Clean logs have different format

### ISSUE THREAD

**Issue by vandalon** [DeebotUniverse/Deebot-4-Home-Assistant#210]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Hi Again,

I still see a few errors on HA startup:

```
2022-07-07 15:36:41 WARNING (MainThread) [deebot_client.commands.clean_logs] Skipping log entry: {'ts': 1656660873, 'last': 0, 'area': 0, 'id': '4a0cb92c-9861-4f56-a5d0-ace21b09b930@1331760851@8KTk', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/4a0cb92c-9861-4f56-a5d0-ace21b09b930@1331760851@8KTk', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'aiopen': 1, 'powerMopType': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/deebot_client/commands/clean_logs.py", line 42, in _handle_requested
    stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
2022-07-07 15:36:41 WARNING (MainThread) [deebot_client.commands.clean_logs] Skipping log entry: {'ts': 1655551621, 'last': 5, 'area': 0, 'id': '4a0cb92c-9861-4f56-a5d0-ace21b09b930@1608006014@8KTk', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/4a0cb92c-9861-4f56-a5d0-ace21b09b930@1608006014@8KTk', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'aiopen': 1, 'powerMopType': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/deebot_client/commands/clean_logs.py", line 42, in _handle_requested
    stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
```

### Diagnostics information

[deebot-f24a3fd5f5cd9571101b6dc67f38cd09-Mega.Maid-974c1ad186ae501a46a58d8b8a2fba11.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/9064181/deebot-f24a3fd5f5cd9571101b6dc67f38cd09-Mega.Maid-974c1ad186ae501a46a58d8b8a2fba11.json.txt)

**Comment by edenhaus** [comment]
This are not errors, but warnings. In your entries the `stopReason` is missing. We will skip this entries and the sensor last_cleaning will continue to work without it.

Can you please verify with the app, why this entries don't have a `stopReason`? Are they another type of cleaning or something else?

**Comment by vandalon** [comment]
![image](https://user-images.githubusercontent.com/3370317/177837399-1cde98e8-f0fd-484f-8301-0f39470331ff.png)

Does this help?

**Comment by vandalon** [comment]
Anything new on this?

**Comment by mrbungle64** [comment]
@vandalon

> Anything new on this?

fyi: @edenhaus is currently on an extended vacation.
It will probably take at least 1 month until he will be active here again.
