### ISSUE TITLE
ha2022.7.0b0 issue

### ISSUE THREAD

**Issue by zender555** [DeebotUniverse/Deebot-4-Home-Assistant#222]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Unexpected exception importing platform custom_components.deebot.config_flow

### Diagnostics information

Logger: homeassistant.loader
Source: custom_components/deebot/hub.py:9
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 19:10:37 (4 occurrences)
Last logged: 19:36:23

Unexpected exception importing platform custom_components.deebot.config_flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/deebot/__init__.py", line 12, in <module>
    from . import hub
  File "/config/custom_components/deebot/hub.py", line 9, in <module>
    from deebot_client import Configuration, create_instances
  File "/usr/local/lib/python3.9/site-packages/deebot_client/__init__.py", line 4, in <module>
    from ._api_client import _InternalApiClient
  File "/usr/local/lib/python3.9/site-packages/deebot_client/_api_client.py", line 10, in <module>
    from .models import Configuration, Credentials
  File "/usr/local/lib/python3.9/site-packages/deebot_client/models.py", line 9, in <module>
    class DeviceInfo(dict):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/models.py", line 28, in DeviceInfo
    def nick(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by edenhaus** [comment]
As written in the release notes of [2022.7](https://www.home-assistant.io/blog/2022/07/06/release-20227/#improved-stability-and-performance-and-python-310) HA is running now on python 3.10.

Version 1.4.0 and above require HA 2022.7 and implizit python 3.10.

I think you run HA in your own python environment with a python version below 3.10

If you can't upgrade your python version that use a version below 1.4.0 of this integration 

P.S. Please use the stable 2022.7 release as it is already released.
