### ISSUE TITLE
Could not parse getMapSet

### ISSUE THREAD

**Issue by hydazz** [DeebotUniverse/Deebot-4-Home-Assistant#224]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The integration worked when I first set it up, but now I'm getting errors (see below) and the map generated is missing walls.
I am using an unsupported DEEBOT T10 Plus, but as it used to work I assume something simple has gone wrong. 

[Map](https://imgur.com/a/zXUL6Lw)

### Diagnostics information

[deebot-027f7c457403d858eec6941430aa808f-Servant-64362607e106812db671ae1fb31caa4c.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/9180246/deebot-027f7c457403d858eec6941430aa808f-Servant-64362607e106812db671ae1fb31caa4c.json.txt)

### Anything in the logs that might be useful for us?

```txt
2022-07-25 07:40:07 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '2146471922'}
Traceback (most recent call last):
File "/config/.local/lib/python3.10/site-packages/deebot_client/message.py", line 52, in wrapper
response = func(cls, event_bus, data)
File "/config/.local/lib/python3.10/site-packages/deebot_client/message.py", line 108, in __handle_body_data
return cls._handle_body_data(event_bus, data)
File "/config/.local/lib/python3.10/site-packages/deebot_client/message.py", line 97, in _handle_body_data
return cls._handle_body_data_dict(event_bus, data)
File "/config/.local/lib/python3.10/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
subsets = [int(subset["mssid"]) for subset in data["subsets"]]
KeyError: 'subsets'
2022-07-25 20:07:11 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by edenhaus** [comment]
Can you please activate debug logs and post them here?
