### ISSUE TITLE
Can’t add integration

### ISSUE THREAD

**Issue by chenyc1995** [DeebotUniverse/Deebot-4-Home-Assistant#227]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Showing `This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant` when adding integration

### On which deebot vacuum you have the issue?

710

### Which version of the Deebot component are you using?

1.4.1

### Which version of Home Assistant are you using?

2022.7.7

### What type of installation are you running?

Home Assistant Core

### Country

Nothing

### Continent

Nothing

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```
Logger: homeassistant.config_entries
Source: config_entries.py:784 
First occurred: 00:00:53 (3 occurrences) 
Last logged: 00:19:02

Error occurred loading configuration flow for integration deebot: Exception importing custom_components.deebot.config_flow
```

```

Logger: homeassistant.loader
Source: custom_components/deebot/hub.py:9 
Integration: Deebot 4 Home Assistant (documentation, issues) 
First occurred: 00:00:53 (3 occurrences) 
Last logged: 00:19:02

Unexpected exception importing platform custom_components.deebot.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/deebot/__init__.py", line 12, in <module>
    from . import hub
  File "/home/homeassistant/.homeassistant/custom_components/deebot/hub.py", line 9, in <module>
    from deebot_client import Configuration, create_instances
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/__init__.py", line 4, in <module>
    from ._api_client import _InternalApiClient
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/_api_client.py", line 10, in <module>
    from .models import Configuration, Credentials
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 9, in <module>
    class DeviceInfo(dict):
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 28, in DeviceInfo
    def nick(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'


```

**Comment by mrbungle64** [comment]
@chenyc1995 

The Deebot 710 is currently not supported by the deebot-client library (used by Deebot for Home Assistant)
https://deebot.readthedocs.io/home/faq/
https://deebot.readthedocs.io/home/models/#deebot-client
because it uses a different protocol for communication.

But you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).

**Comment by chenyc1995** [comment]
The issue is not related with robot model. Integration can't be add successfully. But thanks for your reminding.

**Comment by mrbungle64** [comment]
@chenyc1995 

https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/222#issuecomment-1191832888

**Comment by mrbungle64** [comment]
@chenyc1995 

Can we close this issue?
