### ISSUE TITLE
This integration does not support configuration via the UI

### ISSUE THREAD

**Issue by playwithittoo** [DeebotUniverse/Deebot-4-Home-Assistant#228]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hi all
Any help you can give me would be appreciated. I went to update to 1.41 and I started receiving errors that Deebot would not start. It would not let me remove by Ui. I stopped HA core and deleted the deebot folder under custom_components. I changed hacs.repositories to false for installed and null for installed version. Restarted core, stopped core, and started again. This allowed hacs to allow me to re-install the repository. When attempting to install the integration, I get the error "This integration does not support configuration via the UI" and the installation stops. I have tried this method now with versions 1.41, 1.40, 1.32, 1.31 with the same issue. Previously deebot has been working fine for 6 months with no issues. Please help.
Thanx

### On which deebot vacuum you have the issue?

deebot OZMO T8

### Which version of the Deebot component are you using?

1.41

### Which version of Home Assistant are you using?

2022.8.0  also 2022.7.0

### What type of installation are you running?

Home Assistant OS

### Country

ca

### Continent

na

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:796
First occurred: 3:00:02 PM (1 occurrences)
Last logged: 3:00:02 PM

Error occurred loading configuration flow for integration deebot: Exception importing custom_components.deebot.config_flow

Logger: homeassistant.loader
Source: custom_components/deebot/hub.py:11
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 3:00:02 PM (2 occurrences)
Last logged: 3:05:22 PM

Unexpected exception importing platform custom_components.deebot.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 657, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 674, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/deebot/__init__.py", line 12, in <module>
    from . import hub
  File "/config/custom_components/deebot/hub.py", line 11, in <module>
    from deebot_client.mqtt_client import MqttClient
  File "/usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py", line 7, in <module>
    from gmqtt import Client, Subscription
ValueError: source code string cannot contain null bytes
```

**Comment by edenhaus** [comment]
Did you manually change some files of this integration?
Python cannot read them correctly

**Comment by agonybroccoli** [comment]
I can’t set up at all from the UI. Installed via HACS and it doesn’t show up when I try to add the integration.

**Comment by edenhaus** [comment]
The problem is probably that during the installation of the dependency `deebot-client` an error occurred. Now not all required files are installed to use the integration, as your logs show.

Do you have the technical skills to reinstall manual `deebot-client` via pip?
Can you please post here the output of the command `cat /usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py`

**Comment by ctaggmk** [comment]
I've got the same issue I think. The Configure option doesn't appear after a download of this integration and a reboot of HA as per standard procedure for HACS integrations.

I get the following from your cat request. Does this help? Looks like client is missing?

root@photon-machine [ /usr/homeassist/custom_components ]# cat /usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py
cat: /usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py: No such file or directory

**Comment by ctaggmk** [comment]
I've got multiple python3.10 directories but no deebot_client directory at all
```
root@photon-machine [ / ]# find . -name "deebot_client"
root@photon-machine [ / ]# find . -name "python3.10"
./usr/lib/python3.10
./usr/bin/python3.10
./var/lib/docker/overlay2/fa95c2662bc07c033ea703ad1fba602f3f4951f17d04c734193444382643537e/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/199708b7d810b5fe2016d7068155c81aae465fee6160a3847616d82a34dfde02/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/f9191e465c2241bf98f53c2dc756bdb2a9d7a96ee30f470a85a7f51d26701ff4/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/01b199387fe3edfbdecff6bd9f948be183d3ef2fb4094d4f118cbdaa7bfd227b/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/5236ae336a84484be7092ec47c132cbb07702dd1a442fa7454564f9ea3f0f9f3/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/761c37b70c56ceeb8d1de784e69d2b96b177c80bcd3fa8d01972c20f914ecc15/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/761c37b70c56ceeb8d1de784e69d2b96b177c80bcd3fa8d01972c20f914ecc15/diff/usr/local/include/python3.10
./var/lib/docker/overlay2/455b65ebcbc201b03653e54b3dc6be42fadffbb82d574ee6f55f94edb9b3349e/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/455b65ebcbc201b03653e54b3dc6be42fadffbb82d574ee6f55f94edb9b3349e/diff/usr/local/include/python3.10
./var/lib/docker/overlay2/5a17c1fdbee11ecdf75f6bf6b0870199d2d0e32ad32ccb74015e56aa27824295/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/606d7bb4f05981d85f704e36bf7f7d2ed4709739611a2bc17173dd7b3830e38e/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/b742dd91bd41d92d2ea843398733394e4cdd04d4e1f0112b4cf1cee5f43c1116/merged/usr/local/lib/python3.10
./var/lib/docker/overlay2/b742dd91bd41d92d2ea843398733394e4cdd04d4e1f0112b4cf1cee5f43c1116/merged/usr/local/bin/python3.10
./var/lib/docker/overlay2/b742dd91bd41d92d2ea843398733394e4cdd04d4e1f0112b4cf1cee5f43c1116/merged/usr/local/include/python3.10
./var/lib/docker/overlay2/58df06a9c533713018f0270bee476a5cd243631e11c4ac0f62ea7a3ae629c3a4/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/1c79b846883fb6e515332c5ab6513c6dcb769e1c14c3b5a3e72d8f30a8ed5da6/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/c148038ac0f0e00324d3d160dd60f5c7327c773113ff88bbd008a5dc596cd2c6/diff/usr/local/lib/python3.10
./var/lib/docker/overlay2/c148038ac0f0e00324d3d160dd60f5c7327c773113ff88bbd008a5dc596cd2c6/diff/usr/local/bin/python3.10
./var/lib/docker/overlay2/c148038ac0f0e00324d3d160dd60f5c7327c773113ff88bbd008a5dc596cd2c6/diff/usr/local/include/python3.10
root@photon-machine [ / ]# 
```

**Comment by edenhaus** [comment]
Can you check your logs, if Home Assistant was able to install all requirements successfully? In other words, if the dependency deebot-client is installed?

**Comment by ctaggmk** [comment]
Only 1 line in the log via cli and HA UI

root@photon-machine [ /usr/homeassist ]# cat home-assistant.log | grep deebot
2022-08-15 16:56:15.596 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Is there somewhere else I should look?

**Comment by ctaggmk** [comment]
I think I've switched on logger for HACS and set it to debug. The log has got a bit longer on a restart but nothing scary! 

2022-08-15 17:28:36.875 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-15 17:29:06.397 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information
2022-08-15 17:29:07.063 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

**Comment by ctaggmk** [comment]
remove and reinstall

root@photon-machine [ /usr/homeassist ]# cat *.log | grep deebot
2022-08-15 17:34:29.618 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Local path is set to /config/custom_components/deebot
2022-08-15 17:34:29.619 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Remote path is set to custom_components/deebot
2022-08-15 17:34:29.624 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/download/1.4.1/deebot.zip
2022-08-15 17:34:30.124 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Download of deebot.zip completed
2022-08-15 17:34:30.140 INFO (SyncWorker_3) [homeassistant.loader] Loaded deebot from custom_components.deebot
2022-08-15 17:34:30.141 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
root@photon-machine [ /usr/homeassist ]#

**Comment by ctaggmk** [comment]
What should I be doing after doing the download and the HA restart? Just to stop me clicking around and waiting for a configure option to pop-up!

**Comment by ctaggmk** [comment]
got this from portainer 

2022-08-15T16:32:07.809496473Z 2022-08-15 17:32:07.808 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Removing

2022-08-15T16:32:07.811170470Z 2022-08-15 17:32:07.810 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Removing /config/custom_components/deebot

2022-08-15T16:33:59.816899850Z 2022-08-15 17:33:59.814 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:00.486482871Z 2022-08-15 17:34:00.481 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:05.380495667Z 2022-08-15 17:34:05.377 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:05.957022169Z 2022-08-15 17:34:05.954 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:12.237066619Z 2022-08-15 17:34:12.234 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:12.841553861Z 2022-08-15 17:34:12.839 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:14.050139957Z 2022-08-15 17:34:14.047 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:14.775158366Z 2022-08-15 17:34:14.772 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:18.448796002Z 2022-08-15 17:34:18.446 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:19.039051691Z 2022-08-15 17:34:19.036 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:26.499850839Z 2022-08-15 17:34:26.497 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:27.094807035Z 2022-08-15 17:34:27.092 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:28.107568479Z 2022-08-15 17:34:28.104 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running pre installation steps

2022-08-15T16:34:28.108726860Z 2022-08-15 17:34:28.104 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Pre installation steps completed

2022-08-15T16:34:28.110167624Z 2022-08-15 17:34:28.105 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running installation steps

2022-08-15T16:34:28.110979482Z 2022-08-15 17:34:28.105 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:34:28.650603731Z 2022-08-15 17:34:28.648 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:34:29.620477073Z 2022-08-15 17:34:29.618 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Local path is set to /config/custom_components/deebot

2022-08-15T16:34:29.621332621Z 2022-08-15 17:34:29.619 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Remote path is set to custom_components/deebot

2022-08-15T16:34:29.622143069Z 2022-08-15 17:34:29.619 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> ref: 1.4.1 --- tag: 1.4.1

2022-08-15T16:34:29.626891255Z 2022-08-15 17:34:29.624 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/download/1.4.1/deebot.zip

2022-08-15T16:34:30.125500733Z 2022-08-15 17:34:30.124 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Download of deebot.zip completed

2022-08-15T16:34:30.127436231Z 2022-08-15 17:34:30.125 DEBUG (SyncWorker_2) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Cleaning up /tmp/tmpaoyh0rbm

2022-08-15T16:34:30.131356440Z 2022-08-15 17:34:30.128 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Installation steps completed

2022-08-15T16:34:30.132384640Z 2022-08-15 17:34:30.128 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running post installation steps

2022-08-15T16:34:30.142070124Z 2022-08-15 17:34:30.140 INFO (SyncWorker_3) [homeassistant.loader] Loaded deebot from custom_components.deebot

2022-08-15T16:34:30.142945433Z 2022-08-15 17:34:30.141 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2022-08-15T16:34:30.152191263Z 2022-08-15 17:34:30.150 INFO (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Post installation steps completed

2022-08-15T16:37:01.396293425Z 2022-08-15 17:37:01.395 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2022-08-15T16:37:32.559422202Z 2022-08-15 17:37:32.552 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:37:33.147814605Z 2022-08-15 17:37:33.146 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

2022-08-15T16:46:28.348018468Z 2022-08-15 17:46:28.345 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Getting repository information

2022-08-15T16:46:28.960376155Z 2022-08-15 17:46:28.957 DEBUG (MainThread) [custom_components.hacs] <Integration DeebotUniverse/Deebot-4-Home-Assistant> Running checks against 1.4.1

      
I think can clearly see it removing, installing and cleaning up. But not much detail

**Comment by DemianTinkiel** [comment]
I have the same result. However, in my logs it is due to
```
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Home Assistant core 2022.8.6 on Raspberry Pi 3b+

full log:
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/deebot/hub.py:9
Integration: Deebot 4 Home Assistant
First occurred: 21:20:07 (1 occurrences)
Last logged: 21:20:07

Unexpected exception importing platform custom_components.deebot.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 657, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 674, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/deebot/__init__.py", line 12, in <module>
    from . import hub
  File "/home/homeassistant/.homeassistant/custom_components/deebot/hub.py", line 9, in <module>
    from deebot_client import Configuration, create_instances
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/__init__.py", line 4, in <module>
    from ._api_client import _InternalApiClient
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/_api_client.py", line 10, in <module>
    from .models import Configuration, Credentials
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 9, in <module>
    class DeviceInfo(dict):
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 28, in DeviceInfo
    def nick(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by edenhaus** [comment]
@DemianTinkiel You need python 3.10 to run this integration as written in #222

**Comment by edenhaus** [comment]
Somehow you didn't install the dependency `deebot-client` correctly. Can you please try to install it on a clean home-assistant container?

**Comment by JBakers** [comment]
> I can’t set up at all from the UI. Installed via HACS and it doesn’t show up when I try to add the integration.

Refresh your browser (CTRL-F5) then it will show up.

**Comment by JBakers** [comment]
I get the same "This integration does not support configuration via the UI"

Log:
 `Logger: homeassistant.loader
Source: custom_components/deebot/hub.py:9
Integration: Deebot 4 Home Assistant ([documentation](https://deebot.readthedocs.io/integrations/home-assistant), [issues](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues))
First occurred: 10:45:01 (1 occurrences)
Last logged: 10:45:01

Unexpected exception importing platform custom_components.deebot.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/deebot/__init__.py", line 12, in <module>
    from . import hub
  File "/home/homeassistant/.homeassistant/custom_components/deebot/hub.py", line 9, in <module>
    from deebot_client import Configuration, create_instances
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/__init__.py", line 4, in <module>
    from ._api_client import _InternalApiClient
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/_api_client.py", line 10, in <module>
    from .models import Configuration, Credentials
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 9, in <module>
    class DeviceInfo(dict):
  File "/srv/homeassistant/lib/python3.9/site-packages/deebot_client/models.py", line 28, in DeviceInfo
    def nick(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

**Comment by edenhaus** [comment]
@JBakers You need python 3.10 to run this integration. As you don't use one of the preffered installation methods of HA, you need manually upgrade to python 3.10
