### ISSUE TITLE
Bumper setup fails

### ISSUE THREAD

**Issue by ajctrl** [DeebotUniverse/Deebot-4-Home-Assistant#306]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

adding this integration fails with following error 

Logger: custom_components.deebot.config_flow
Source: custom_components/deebot/config_flow.py:259
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 04:15:45 (3 occurrences)
Last logged: 04:21:05

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/deebot/config_flow.py", line 81, in async_step_user
    self._devices = await _retrieve_devices(self.hass, data)
  File "/config/custom_components/deebot/config_flow.py", line 259, in _retrieve_devices
    return await api_client.get_devices()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/api_client.py", line 43, in get_devices
    credentials = await self._authenticator.authenticate()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/authentication.py", line 243, in authenticate
    self._credentials = await self._auth_client.login()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/authentication.py", line 73, in login
    login_token_resp = await self.__call_login_by_it_token(user_id, auth_code)
  File "/usr/local/lib/python3.10/site-packages/deebot_client/authentication.py", line 202, in __call_login_by_it_token
    raise AuthenticationError(
deebot_client.exceptions.AuthenticationError: failure it server response error.responseObj: {"code":"9001","msg":"授权码过期！","time":1677125745644,"data":null,"success":false} (1301) for call users/user.do

### On which deebot vacuum you have the issue?

X

### Which version of the Deebot component are you using?

dev

### Which version of Home Assistant are you using?

2023.02

### What type of installation are you running?

Home Assistant OS

### Instance type

Bumper

### Anything in the logs that might be useful for us?

```txt
bumper_1  | client with devid DNCQIIG7 attempting login
bumper_1  | [2023-02-23 04:11:08,514] :: INFO :: confserver :: client with devid DNCQIIG7 attempting login
bumper_1  | Adding new user with userid: tmpuser
bumper_1  | [2023-02-23 04:11:08,519] :: INFO :: bumper :: Adding new user with userid: tmpuser

client with devid DNCQIIG7 attempting login
{"request": {"route_name": "v1_user_login", "method": "GET", "path": "/v1/private/it/EN/DNCQIIG7/global_e/1.6.3/google_play/1/user/login", "query_string": "account=Bumper&password=8500b63132a4f08ad0e93aa4802c3b13&requestId=581161663a1b44253cb8ca72fccdc179&authTimespan=1677128073956&authTimeZone=GMT-8&authSign=65638943f974f9a8321609225923f73f&authAppkey=1520391301804", "raw_path": "/v1/private/it/EN/DNCQIIG7/global_e/1.6.3/google_play/1/user/login?account=Bumper&password=8500b63132a4f08ad0e93aa4802c3b13&requestId=581161663a1b44253cb8ca72fccdc179&authTimespan=1677128073956&authTimeZone=GMT-8&authSign=65638943f974f9a8321609225923f73f&authAppkey=1520391301804", "raw_headers": "(b'Host', b'gl-it-api.ecovacs.com'),(b'User-Agent', b'HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10'),(b'Accept', b'*/*'),(b'Accept-Encoding', b'gzip, deflate')", "body": "None"}, "response": {"status": "200", "body": "{'code': '0000', 'data': {'ucUid': 'fuid_tmpuser', 'loginName': 'fusername_tmpuser', 'mobile': None, 'accessToken': 'ab51d43a61554c80a820ff298f4ad4e2', 'uid': 'fuid_tmpuser', 'username': 'fusername_tmpuser', 'country': 'it', 'email': 'null@null.com'}, 'msg': '\u64cd\u4f5c\u6210\u529f', 'time': 1677095674000}"}}
Adding token ab51d43a61554c80a820ff298f4ad4e2 for userid tmpuser
[2023-02-23 05:54:33,986] :: INFO :: confserver :: confserver :: login :: 535 :: client with devid DNCQIIG7 attempting login
[2023-02-23 05:54:33,991] :: DEBUG :: bumper :: db :: user_add_token :: 138 :: Adding token ab51d43a61554c80a820ff298f4ad4e2 for userid tmpuser
[2023-02-23 05:54:34,000] :: DEBUG :: confserver :: confserver :: log_all_requests :: 254 :: {"request": {"route_name": "v1_user_login", "method": "GET", "path": "/v1/private/it/EN/DNCQIIG7/global_e/1.6.3/google_play/1/user/login", "query_string": "account=Bumper&password=8500b63132a4f08ad0e93aa4802c3b13&requestId=581161663a1b44253cb8ca72fccdc179&authTimespan=1677128073956&authTimeZone=GMT-8&authSign=65638943f974f9a8321609225923f73f&authAppkey=1520391301804", "raw_path": "/v1/private/it/EN/DNCQIIG7/global_e/1.6.3/google_play/1/user/login?account=Bumper&password=8500b63132a4f08ad0e93aa4802c3b13&requestId=581161663a1b44253cb8ca72fccdc179&authTimespan=1677128073956&authTimeZone=GMT-8&authSign=65638943f974f9a8321609225923f73f&authAppkey=1520391301804", "raw_headers": "(b'Host', b'gl-it-api.ecovacs.com'),(b'User-Agent', b'HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10'),(b'Accept', b'*/*'),(b'Accept-Encoding', b'gzip, deflate')", "body": "None"}, "response": {"status": "200", "body": "{'code': '0000', 'data': {'ucUid': 'fuid_tmpuser', 'loginName': 'fusername_tmpuser', 'mobile': None, 'accessToken': 'ab51d43a61554c80a820ff298f4ad4e2', 'uid': 'fuid_tmpuser', 'username': 'fusername_tmpuser', 'country': 'it', 'email': 'null@null.com'}, 'msg': '\u64cd\u4f5c\u6210\u529f', 'time': 1677095674000}"}}
[2023-02-23 05:54:34,001] :: DEBUG :: aiohttp.access :: web_log :: log :: 233 :: 172.19.0.3 [23/Feb/2023:04:54:33 +0000] "GET /v1/private/it/EN/DNCQIIG7/global_e/1.6.3/google_play/1/user/login?account=Bumper&password=8500b63132a4f08ad0e93aa4802c3b13&requestId=581161663a1b44253cb8ca72fccdc179&authTimespan=1677128073956&authTimeZone=GMT-8&authSign=65638943f974f9a8321609225923f73f&authAppkey=1520391301804 HTTP/1.1" 200 467 "-" "HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10"
{"request": {"route_name": "v1_global_auth_getAuthCode", "method": "GET", "path": "/v1/global/auth/getAuthCode", "query_string": "uid=fuid_tmpuser&accessToken=ab51d43a61554c80a820ff298f4ad4e2&bizType=ECOVACS_IOT&deviceId=DNCQIIG7&authTimespan=1677128074005&authSign=08e5e1148b46a6b6a6a2eaad43df8ec9&authAppkey=1520391491841", "raw_path": "/v1/global/auth/getAuthCode?uid=fuid_tmpuser&accessToken=ab51d43a61554c80a820ff298f4ad4e2&bizType=ECOVACS_IOT&deviceId=DNCQIIG7&authTimespan=1677128074005&authSign=08e5e1148b46a6b6a6a2eaad43df8ec9&authAppkey=1520391491841", "raw_headers": "(b'Host', b'gl-it-openapi.ecovacs.com'),(b'User-Agent', b'HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10'),(b'Accept', b'*/*'),(b'Accept-Encoding', b'gzip, deflate')", "body": "None"}, "response": {"status": "200", "body": "{'code': '0000', 'data': {'authCode': 'us_0f93f54373dd4d5a9134750979e62dc7', 'ecovacsUid': 'fuid_tmpuser'}, 'msg': '\u64cd\u4f5c\u6210\u529f', 'time': 1677095674042}"}}
[2023-02-23 05:54:34,042] :: DEBUG :: confserver :: confserver :: log_all_requests :: 254 :: {"request": {"route_name": "v1_global_auth_getAuthCode", "method": "GET", "path": "/v1/global/auth/getAuthCode", "query_string": "uid=fuid_tmpuser&accessToken=ab51d43a61554c80a820ff298f4ad4e2&bizType=ECOVACS_IOT&deviceId=DNCQIIG7&authTimespan=1677128074005&authSign=08e5e1148b46a6b6a6a2eaad43df8ec9&authAppkey=1520391491841", "raw_path": "/v1/global/auth/getAuthCode?uid=fuid_tmpuser&accessToken=ab51d43a61554c80a820ff298f4ad4e2&bizType=ECOVACS_IOT&deviceId=DNCQIIG7&authTimespan=1677128074005&authSign=08e5e1148b46a6b6a6a2eaad43df8ec9&authAppkey=1520391491841", "raw_headers": "(b'Host', b'gl-it-openapi.ecovacs.com'),(b'User-Agent', b'HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10'),(b'Accept', b'*/*'),(b'Accept-Encoding', b'gzip, deflate')", "body": "None"}, "response": {"status": "200", "body": "{'code': '0000', 'data': {'authCode': 'us_0f93f54373dd4d5a9134750979e62dc7', 'ecovacsUid': 'fuid_tmpuser'}, 'msg': '\u64cd\u4f5c\u6210\u529f', 'time': 1677095674042}"}}
[2023-02-23 05:54:34,045] :: DEBUG :: aiohttp.access :: web_log :: log :: 233 :: 172.19.0.3 [23/Feb/2023:04:54:34 +0000] "GET /v1/global/auth/getAuthCode?uid=fuid_tmpuser&accessToken=ab51d43a61554c80a820ff298f4ad4e2&bizType=ECOVACS_IOT&deviceId=DNCQIIG7&authTimespan=1677128074005&authSign=08e5e1148b46a6b6a6a2eaad43df8ec9&authAppkey=1520391491841 HTTP/1.1" 200 323 "-" "HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10"
Scheduling Ping
[2023-02-23 05:54:41,313] :: DEBUG :: hbmqtt.mqtt.protocol.handler :: client_handler :: handle_write_timeout :: 91 :: Scheduling Ping
```

### Additional information
ECOVACS HOME 2.1.0 -> OK

**Comment by edenhaus** [comment]
Do you have setup correctly a bumper instance? Can you access the bumper ui?

**Comment by ajctrl** [comment]
yes, bumper, apps, sucks are working fine

**Comment by edenhaus** [comment]
- Authentication is disabled on bumper?
- Which exact version of the bumper image are you using?
- Did you select during the config floe setup in HA the instance type bumper?

**Comment by ajctrl** [comment]
* Authentication is disabled on bumper?
yes, it's just a vanilla container
 * Which exact version of the bumper image are you using?
latest docker image: bmartin5692/bumper
 * Did you select during the config floe setup in HA the instance type bumper?
the same error occurs in both bumper / cloud  setups.

**Comment by edenhaus** [comment]
You need to select bumper otherwise it will not work.

Can you please verify that the dns redircet setup is also working for the HA container?

**Comment by ajctrl** [comment]
thank you very much!
dns in home assistant wasn't working as expected.
