### ISSUE TITLE
async_setup_platforms deprecated from 2023.5 onwards

### ISSUE THREAD

**Issue by dreamtheater39** [DeebotUniverse/Deebot-4-Home-Assistant#340]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

async_setup_platforms used in init.py is deprecated from the latest HA Core (2023.5.b0 onwards)

### Diagnostics information

2023.5.b0

**Comment by edenhaus** [comment]
Can you please attach the diagnostic information of this component or at least the version which are you using?

**Comment by eight10man** [comment]
Logger: homeassistant.config_entries
Source: custom_components/deebot/hub.py:68
Integration: Deebot 4 Home Assistant ([documentation](https://deebot.readthedocs.io/integrations/home-assistant), [issues](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues))
First occurred: 9:36:30 PM (1 occurrences)
Last logged: 9:36:30 PM

Error setting up entry ECD1JHNR for deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/deebot/__init__.py", line 75, in async_setup_entry
    await deebot_hub.async_setup()
  File "/config/custom_components/deebot/hub.py", line 68, in async_setup
    await self._mqtt.initialize()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py", line 92, in initialize
    await self._client.connect(
  File "/usr/local/lib/python3.10/site-packages/gmqtt/client.py", line 225, in connect
    self._connection = await self._create_connection(
  File "/usr/local/lib/python3.10/site-packages/gmqtt/client.py", line 241, in _create_connection
    connection = await MQTTConnection.create_connection(host, port, ssl, clean_session, keepalive)
  File "/usr/local/lib/python3.10/site-packages/gmqtt/mqtt/connection.py", line 27, in create_connection
    transport, protocol = await loop.create_connection(MQTTProtocol, host, port, ssl=ssl)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

**Comment by edenhaus** [comment]
@eight10man Please post only information related to this topic. If you have the same problem, than please report which version you are using? The best would as requested above to share the whole diagnostic information. It contains all information, version, which I need

**Comment by dreamtheater39** [comment]
The issue seems to have resolved itself. The problem existed only on one of
the beta releases of 2023.5

**Comment by edenhaus** [comment]
Thanks for thr Information
