### ISSUE TITLE
Skipping log entry - 5 is not a valid CleanJobStatus

### ISSUE THREAD

**Issue by MiddleSiggy** [DeebotUniverse/Deebot-4-Home-Assistant#350]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I get this warning every once in a while, here is the log entry that is produced:

2023-05-19 16:24:28.791 WARNING (MainThread) [deebot_client.commands.clean_logs] Skipping log entry: {'ts': 1683142200, 'last': 2187, 'area': 29, 'id': 'cd435c44-0601-4aee-8a8f-85ed30e6cfd8@438871403@MzKM', 'imageUrl': 'https://portal-na
.ecouser.net/api/lg/image/cd435c44-0601-4aee-8a8f-85ed30e6cfd8@438871403@MzKM', 'type': 'spotArea', 'aiavoid': 0, 'aitypes': [], 'stopReason': 5, 'aiopen': 1, 'powerMopType': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/deebot_client/commands/clean_logs.py", line 42, in _handle_requested
    stop_reason=CleanJobStatus(
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 5 is not a valid CleanJobStatus

Let me know if I can help in any way.. 

### Diagnostics information

I have three devices how do I find the right one?

### Anything in the logs that might be useful for us?

```txt
Just looking through my log file and I found this, figured I would share
```

**Comment by edenhaus** [comment]
Can you please identify the cleanlog entry, which throws the above error in the app and check what status the app will display?

Currently only 1-3 are recognized as you can see [here](https://github.com/DeebotUniverse/client.py/blob/c910627c317afad2336250503ecaafc0fb6f91b6/deebot_client/events/__init__.py#L31)
