### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by Anashost** [DeebotUniverse/Deebot-4-Home-Assistant#371]
### Question

Is it just me or the map is not available?
Deebot N8 Pro

**Comment by edenhaus** [comment]
Didi you enable the camera entity?
https://deebot.readthedocs.io/integrations/home-assistant/entities/

**Comment by Anashost** [comment]
Already enabled, it was showing before, but all of the sudden no more map (all other functions still works). I actually did replace the vacuum location in my home around the time it stopped working, but the map didn't reset in the ecovacs app. So I don't know if this has to do with this issue.

I've tried reinstalling deebot 4 home assistant from hacs but still no map.

**Comment by Anashost** [comment]
![Screenshot_20230626_182738_Home Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/41167157/420ee359-69c3-4d7e-be63-880dd79b83e2)

**Comment by edenhaus** [comment]
Can you please check the log for messages about the map?

**Comment by Anashost** [comment]
Sure:

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/deebot/camera.py:64
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 6:32:23 PM (4 occurrences)
Last logged: 6:32:24 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 738, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 756, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 172, in _async_get_image
    if image_bytes := await camera.async_camera_image(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deebot/camera.py", line 64, in async_camera_image
    return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/map.py", line 316, in get_base64_map
    _draw_subset(subset, draw, image_box)
  File "/usr/local/lib/python3.11/site-packages/deebot_client/map.py", line 127, in _draw_subset
    draw.dashed_line(points, dash=(3, 2), fill=_COLORS[subset.type], width=1)
  File "/usr/local/lib/python3.11/site-packages/deebot_client/map.py", line 499, in dashed_line
    start = position / length
            ~~~~~~~~~^~~~~~~~
ZeroDivisionError: float division by zero

```

**Comment by Anashost** [comment]
@edenhaus 
I always do room or custom cleaning only, but did an Auto cleaning in the app today and the map came back in home assistant. No idea why!

**Comment by edenhaus** [comment]
If the issue happens agains please open a bug issue
