### ISSUE TITLE
[deebot_client.commands.clean_logs] Skipping log entry

### ISSUE THREAD

**Issue by rwez** [DeebotUniverse/Deebot-4-Home-Assistant#378]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

```
2023-07-07 14:39:30.093 WARNING (MainThread) [deebot_client.commands.clean_logs] Skipping log entry: {'ts': 1687881600, 'last': 0, 'area': 0, 'id': '173c3012-fe11-49f0-967b-5071bb5b9632@39827395@aQaw', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/173c3012-fe11-49f0-967b-5071bb5b9632@39827395@aQaw', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'stopReason': 5, 'aiopen': 1, 'powerMopType': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/deebot_client/commands/clean_logs.py", line 70, in _handle_response
    stop_reason=CleanJobStatus(
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 5 is not a valid CleanJobStatus
2023-07-07 14:39:30.097 WARNING (MainThread) [deebot_client.commands.clean_logs] Skipping log entry: {'ts': 1686412800, 'last': 0, 'area': 0, 'id': '173c3012-fe11-49f0-967b-5071bb5b9632@1995891957@aQaw', 'imageUrl': 'https://portal-eu.ecouser.net/api/lg/image/173c3012-fe11-49f0-967b-5071bb5b9632@1995891957@aQaw', 'type': 'auto', 'aiavoid': 0, 'aitypes': [], 'stopReason': 5, 'aiopen': 1, 'powerMopType': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/deebot_client/commands/clean_logs.py", line 70, in _handle_response
    stop_reason=CleanJobStatus(
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 5 is not a valid CleanJobStatus
```

### Diagnostics information

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.7.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "5.14.0-284.18.1.el9_2.x86_64",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "truenas": {
      "version": "0.0.0",
      "requirements": []
    },
    "cellar_tracker": {
      "version": "20210413",
      "requirements": [
        "cellartracker"
      ]
    },
    "imou_life": {
      "version": "1.0.13",
      "requirements": [
        "imouapi==1.0.13"
      ]
    },
    "hon": {
      "version": "0.9.0-beta.8",
      "requirements": [
        "pyhOn==0.14.7"
      ]
    },
    "deebot": {
      "version": "1.6.1",
      "requirements": [
        "deebot-client==2.0.0",
        "numpy>=1.21.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "deebot",
    "name": "Deebot 4 Home Assistant",
    "codeowners": [
      "@DeebotUniverse",
      "@edenhaus"
    ],
    "config_flow": true,
    "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues",
    "loggers": [
      "custom_components.deebot",
      "deebot_client",
      "gmqtt"
    ],
    "requirements": [
      "deebot-client==2.0.0",
      "numpy>=1.21.2"
    ],
    "version": "1.6.1",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "1ae06a77ebf7ce3a56241d2e32a42e82",
      "version": 4,
      "domain": "deebot",
      "title": "**REDACTED**",
      "data": {
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "country": "nl",
        "continent": "eu"
      },
      "options": {
        "devices": "**REDACTED**"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "device": {
      "did": "**REDACTED**",
      "name": "**REDACTED**",
      "class": "h18jkh",
      "resource": "aQaw",
      "nick": "deebot",
      "company": "eco-ng",
      "bindTs": 1670252965328,
      "service": {
        "jmq": "jmq-ngiot-eu.dc.ww.ecouser.net",
        "mqs": "api-ngiot.dc-as.ww.ecouser.net"
      },
      "homeId": "**REDACTED**",
      "homeSort": 1,
      "deviceName": "DEEBOT OZMO T8",
      "icon": "https://portal-ww.ecouser.net/api/pim/file/get/5e8e8d146482551d72530e47",
      "ota": true,
      "UILogicId": "DT_8G",
      "materialNo": "110-1921-0400",
      "pid": "5e8e8d2a032edd3c03c66bf7",
      "product_category": "DEEBOT",
      "model": "OT8G",
      "updateInfo": {
        "needUpdate": false,
        "changeLog": ""
      },
      "status": 1,
      "offmap": true,
      "otaUpgrade": {}
    }
  }
}
```

**Comment by edenhaus** [comment]
Can you please check, what stopReason=5 means? What shows the app?

**Comment by rwez** [comment]
I have no message in the app which indicates a fault or a message like stopreason=5. there was a message about the anti-dropsensor not being clean. I have cleared that message, but that did not seem to help.
