### ISSUE TITLE
Integration doesn't work since update to newest version hassio

### ISSUE THREAD

**Issue by larbre86** [DeebotUniverse/Deebot-4-Home-Assistant#411]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Since the last update to newest version of homeassistant, the entitys of my deebot aren't avaible anymore.
I checked every part of the system, anywhere is an reportet issue to the integration.

I have an X1 Omni.

It worked fine for me until the update yesterday.

best regards

larbre86

### Diagnostics information

[deebot-2b59e8deea496997d828018451382f5d-Yiko-90e35e924bcfd600a190e5edd9930b01.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/12451021/deebot-2b59e8deea496997d828018451382f5d-Yiko-90e35e924bcfd600a190e5edd9930b01.json.txt)

**Comment by edenhaus** [comment]
Can you please describe what you mean by "avaible anymore"? Did you verify that they are activated?
What is written in the logs? Please share debug logs

**Comment by larbre86** [comment]
Wow, thanks for the fast answer.
All entitys are activated but not avaible.

Here is the log. It seem's like an api error?

deebot_client.exceptions.ApiError: Unknown error occurred
2023-08-28 08:22:40.093 WARNING (MainThread) [deebot_client.mqtt_client] Connection lost; Reconnecting in 5 seconds ...
  File "/usr/local/lib/python3.11/site-packages/deebot_client/mqtt_client.py", line 160, in mqtt
2023-08-28 08:24:09.128 DEBUG (MainThread) [deebot_client.authentication] No cached credentials, performing login
2023-08-28 08:24:09.128 DEBUG (MainThread) [deebot_client.authentication] Start login to EcovacsAPI
2023-08-28 08:24:09.128 DEBUG (MainThread) [deebot_client.authentication] calling login api
2023-08-28 08:24:09.431 DEBUG (MainThread) [deebot_client.authentication] got {'code': '0000', 'msg': '操作成功', 'time': 1693203849220, 'data': {'uid': '[REMOVED]', 'accessToken': '[REMOVED]', 'userName': '[REMOVED]', 'email': '[REMOVED]', 'mobile': '[REMOVED]', 'isNew': None, 'loginName': '[REMOVED]', 'ucUid': '[REMOVED]'}, 'success': True}
2023-08-28 08:24:09.432 DEBUG (MainThread) [deebot_client.authentication] calling auth api
2023-08-28 08:24:09.542 DEBUG (MainThread) [deebot_client.authentication] got {'code': '0000', 'msg': '操作成功', 'time': 1693203849529, 'data': {'authCode': '[REMOVED]', 'ecovacsUid': '[REMOVED]'}, 'success': True}
2023-08-28 08:24:09.543 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/users/user.do, params=None, json={'edition': 'ECOGLOBLE', 'userId': '20220916171942_81b2ea851d05db7d51b1730185161a7e', 'token': 'GLOBAL_APP_ECOVACS_IOT_ebad95e00ea1e66d30d9b2bdac7dee6a', 'realm': 'ecouser.net', 'resource': 'JCPGZXCX', 'org': 'ECOWW', 'last': '', 'country': 'DE', 'todo': 'loginByItToken'}
2023-08-28 08:24:09.648 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/users/user.do, params=None, json={'edition': 'ECOGLOBLE', 'userId': '20220916171942_81b2ea851d05db7d51b1730185161a7e', 'token': 'GLOBAL_APP_ECOVACS_IOT_ebad95e00ea1e66d30d9b2bdac7dee6a', 'realm': 'ecouser.net', 'resource': 'JCPGZXCX', 'org': 'ECOWW', 'last': '', 'country': 'DE', 'todo': 'loginByItToken'}, response={'todo': 'result', 'result': 'ok', 'userId': '[REMOVED]', 'resource': 'JCPGZXCX', 'token': '[REMOVED]', 'last': 604800000}
2023-08-28 08:24:09.649 DEBUG (MainThread) [deebot_client.authentication] Switching to shorter UID
2023-08-28 08:24:09.649 DEBUG (MainThread) [deebot_client.authentication] Login to EcovacsAPI successfully
2023-08-28 08:24:09.650 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/appsvr/app.do, params=None, json={'userid': 'giqptjm7f74d9810', 'todo': 'GetGlobalDeviceList'}
2023-08-28 08:24:09.703 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/appsvr/app.do, params=None, json={'userid': 'giqptjm7f74d9810', 'todo': 'GetGlobalDeviceList'}, response={'code': 0, 'todo': 'result', 'ret': 'ok', 'devices': [{'did': '[REMOVED]', 'name': 'E06115513D1FP5WD0534', 'class': '1vxt52', 'resource': 's3so', 'nick': 'Yiko', 'company': 'eco-ng', 'bindTs': 1663342393917, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-as.ww.ecouser.net'}, 'homeId': '632494136fb015ebb0ba03f6', 'homeSort': 1, 'deviceName': 'DEEBOT X1 OMNI', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/6225bd1c2af2127804f540e5', 'ota': True, 'UILogicId': 't10_ww_n_omni', 'materialNo': '110-2102-0300', 'pid': '6185e29610683da4d6a7a9cd', 'product_category': 'DEEBOT', 'model': 'EINSTEIN_INT', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'status': 0, 'offmap': True, 'otaUpgrade': {}}]}
2023-08-28 08:24:40.247 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693203880.247511, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}
2023-08-28 08:24:40.345 DEBUG (MainThread) [deebot_client.authentication] Error calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693203880.247511, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}, response=<ClientResponse(https://portal-eu.ecouser.net/api/iot/devmanager.do?mid=1vxt52&did=eb80ba43-936a-4ed6-9978-a0a955915031&td=q&u=giqptjm7f74d9810&cv=1.67.3&t=a&av=1.3.1) [502 Bad Gateway]>
2023-08-28 08:24:40.346 DEBUG (MainThread) [deebot_client.authentication] Error: url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693203880.247511, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 267, in post
2023-08-28 08:24:40.348 INFO (MainThread) [deebot_client.authentication] Retry calling API due 502: Unfortunately the ecovacs api is unreliable. Retrying in 10 seconds
2023-08-28 08:24:45.385 DEBUG (MainThread) [deebot_client.mqtt_client.client] Sending PINGREQ
2023-08-28 08:24:45.403 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PINGRESP
2023-08-28 08:24:50.349 DEBUG (MainThread) [deebot_client.authentication] Calling api(2/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693203880.247511, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}
2023-08-28 08:24:50.378 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693203880.247511, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}, response={'ret': 'fail', 'errno': 4200, 'error': 'endpoint offline', 'debug': 'jmq.clusterNode.FetchClientInfo rsp==null; no clientinfo in redis which means no ping was received from endpoint for a long time'}
2023-08-28 08:24:50.378 INFO (MainThread) [deebot_client.commands.common] Vacuum is offline. Could not execute command "getBattery"
2023-08-28 08:24:50.379 DEBUG (MainThread) [deebot_client.events.event_bus] Event is the same! Skipping (AvailabilityEvent(available=False))
2023-08-28 08:24:50.381 DEBUG (MainThread) [deebot_client.events.event_bus] Event is the same! Skipping (AvailabilityEvent(available=False))
2023-08-28 08:25:45.462 DEBUG (MainThread) [deebot_client.mqtt_client.client] Sending PINGREQ
2023-08-28 08:25:45.483 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PINGRESP
2023-08-28 08:52:44.034 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693205564.034136, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}
2023-08-28 08:52:44.145 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': '1vxt52', 'did': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'td': 'q', 'u': 'giqptjm7f74d9810', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1693205564.034136, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': 'eb80ba43-936a-4ed6-9978-a0a955915031', 'toRes': 's3so', 'toType': '1vxt52'}, response={'ret': 'fail', 'errno': 4200, 'error': 'endpoint offline', 'debug': 'jmq.clusterNode.FetchClientInfo rsp==null; no clientinfo in redis which means no ping was received from endpoint for a long time'}
2023-08-28 08:52:44.146 INFO (MainThread) [deebot_client.commands.common] Vacuum is offline. Could not execute command "getBattery"
2023-08-28 08:52:44.146 DEBUG (MainThread) [deebot_client.events.event_bus] Event is the same! Skipping (AvailabilityEvent(available=False))
2023-08-28 08:52:44.146 DEBUG (MainThread) [deebot_client.events.event_bus] Event is the same! Skipping (AvailabilityEvent(available=False))
2023-08-28 08:52:48.145 DEBUG (MainThread) [deebot_client.mqtt_client.client] Sending PINGREQ
2023-08-28 08:52:48.164 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PINGRESP

**Comment by larbre86** [comment]
Sorry for the issue, i don't know how, but the robot was offline.
I will check this. No issue with the integration.

Sorry!

**Comment by maxime1992** [comment]
Just had the same thing after upgrading to HA `2023.8.4`

![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/4950209/765f0203-340b-4786-81c6-d5c333bf3e71)

Logs:

```
Logger: homeassistant.setup
Source: lsiopy/lib/python3.11/site-packages/deebot_client/mqtt_client.py:10
First occurred: 10:24:24 (1 occurrences)
Last logged: 10:24:24

Setup failed for custom integration deebot: Unable to import component: No module named 'asyncio_mqtt'
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/deebot/__init__.py", line 20, in <module>
    from . import hub
  File "/config/custom_components/deebot/hub.py", line 12, in <module>
    from deebot_client.mqtt_client import MqttClient, MqttConfiguration
  File "/config/lsiopy/lib/python3.11/site-packages/deebot_client/mqtt_client.py", line 10, in <module>
    from asyncio_mqtt import Client, Message, MqttError
ModuleNotFoundError: No module named 'asyncio_mqtt'
```

**Comment by maxime1992** [comment]
NVM, just found the update in HACS. Working since I updated.
