### ISSUE TITLE
Recurring error - Could not execute command getError

### ISSUE THREAD

**Issue by EDIflyer** [DeebotUniverse/Deebot-4-Home-Assistant#450]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Recurring error in logs, maps not showing

### Diagnostics information

I just get 'failed, no file' when I click that?
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/13610277/7297d558-1200-427b-9e1e-27044ceee5af)

### Anything in the logs that might be useful for us?

```txt
Logger: deebot_client.command
Source: /usr/local/lib/python3.11/site-packages/deebot_client/command.py:75
First occurred: 21 October 2023 at 19:58:24 (4064 occurrences)
Last logged: 11:42:25

Could not execute command getError
Could not execute command getMapSubSet
Could not execute command getStats
Could not execute command getBattery
Could not execute command getMapSet
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 62, in execute
    result = await self._execute(authenticator, device_info, event_bus)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 86, in _execute
    response = await self._execute_api_request(authenticator, device_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/command.py", line 139, in _execute_api_request
    return await authenticator.post_authenticated(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 361, in post_authenticated
    return await self._auth_client.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 247, in post
    async with self._config.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host portal-ww.ecouser.net:443 ssl:True [None]
```
```


### Additional information

_No response_

**Comment by edenhaus** [comment]
Please check your internet connection as HA cannot connect to the ecovacs servers as you can see in `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host portal-ww.ecouser.net:443 ssl:True [None]`

Not sure how your setup looks like but something is not correct with your network/internet

**Comment by EDIflyer** [comment]
OK, thanks @edenhaus - I'm on Three Mobile Broadband and have noticed a couple of connection issues with SSL recently, I wonder if it could be related - will have a look.

**Comment by EDIflyer** [comment]
Still investigating with my broadband supplier.
