### ISSUE TITLE
Continuous MQTT reconnect

### ISSUE THREAD

**Issue by StefanoGiu** [DeebotUniverse/Deebot-4-Home-Assistant#503]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

2024-01-10 16:26:57.037 WARNING (MainThread) [deebot_client.mqtt_client] Connection lost; Reconnecting in 5 seconds ...
Traceback (most recent call last):
  File "YYYYsite-packages\deebot_client\mqtt_client.py", line 166, in mqtt
    async with (await self._get_client()) as client:
  File "YYYYsite-packages\aiomqtt\client.py", line 1050, in __aenter__
    await self.connect()
  File "YYYYsite-packages\aiomqtt\client.py", line 521, in connect
    await self._wait_for(self._connected, timeout=timeout)
  File "YYYYsite-packages\aiomqtt\client.py", line 855, in _wait_for
    raise MqttError(msg) from None
aiomqtt.error.MqttError: Operation timed out

### Diagnostics information
```json
{
  "home_assistant": {
    "installation_type": "Unknown",
    "version": "2024.1.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": false,
    "arch": "AMD64",
    "timezone": "Europe/Rome",
    "run_as_root": false
  },
  "custom_components": {
    "deebot": {
      "version": "2.0.0",
      "requirements": [
        "deebot-client==3.0.0",
        "numpy>=1.23.2"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "deebot",
    "name": "Deebot 4 Home Assistant",
    "codeowners": [
      "@DeebotUniverse",
      "@edenhaus"
    ],
    "config_flow": true,
    "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues",
    "loggers": [
      "custom_components.deebot",
      "deebot_client"
    ],
    "requirements": [
      "deebot-client==3.0.0",
      "numpy>=1.23.2"
    ],
    "version": "2.0.0",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "53ca82fb15b803bfef81a4b5248f8b7e",
      "version": 4,
      "minor_version": 1,
      "domain": "deebot",
      "title": "**REDACTED**",
      "data": {
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "country": "it",
        "continent": "eu"
      },
      "options": {
        "devices": "**REDACTED**"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "device": {
      "did": "**REDACTED**",
      "name": "**REDACTED**",
      "class": "1vxt52",
      "resource": "y5v4",
      "company": "eco-ng",
      "bindTs": 1698054234866,
      "service": {
        "jmq": "jmq-ngiot-eu.dc.ww.ecouser.net",
        "mqs": "api-ngiot.dc-as.ww.ecouser.net"
      },
      "deviceName": "DEEBOT X1 OMNI",
      "icon": "https://portal-ww.ecouser.net/api/pim/file/get/6225bd1c2af2127804f540e5",
      "ota": true,
      "UILogicId": "t10_ww_n_omni",
      "materialNo": "110-2102-0300",
      "pid": "6185e29610683da4d6a7a9cd",
      "product_category": "DEEBOT",
      "model": "EINSTEIN_INT",
      "updateInfo": {
        "needUpdate": false,
        "changeLog": ""
      },
      "nick": "Aspirapolvere",
      "homeId": "**REDACTED**",
      "homeSort": 1,
      "status": 1,
      "otaUpgrade": {}
    }
  }
}
```

**Comment by edenhaus** [comment]
Closing as unsupported HA installation type
