### ISSUE TITLE
Timeout when setting up bumper

### ISSUE THREAD

**Issue by ulliohura** [DeebotUniverse/Deebot-4-Home-Assistant#519]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

I failed setting up bumper, dont know if its a problem with the docker or with home assistant or anything else. Perhaps you can help me analyzing where the problem is:

- First i'm Running bumper in portainer as a docker on ubuntu vm in proxmox:

```version: "3.6"

networks:
  bumper:
    internal: true

services:
  nginx:
    depends_on:
      - bumper
    image: nginx:alpine
    networks:
      default:
      bumper:
    ports:
      - 443:443
      - 5223:5223
      - 8007:8007
      - 8883:8883
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro # See config file below

  bumper:
    image: bmartin5692/bumper
    restart: unless-stopped
    networks:
      bumper:

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Rome
      BUMPER_ANNOUNCE_IP: 192.168.3.96 # docker-ip
      BUMPER_LISTEN: 192.168.3.72 # deebot-ip
      # BUMPER_DEBUG: "true"
      LOG_TO_STDOUT: "true"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/bumper/data
      - ./certs:/bumper/certs
```

- bumper is composed, but no ports are published, trying to ping it via laptop fails. other ports like portainer-port 9000 are reachable.:

```PS C:\Users\surface> Test-NetConnection 192.168.3.96 -port 8883
WARNUNG: TCP connect to (192.168.3.96 : 8883) failed


ComputerName           : 192.168.3.96
RemoteAddress          : 192.168.3.96
RemotePort             : 8883
InterfaceAlias         : WLAN
SourceAddress          : 192.168.3.45
PingSucceeded          : True
PingReplyDetails (RTT) : 3 ms
TcpTestSucceeded       : False
```

2nd: pihole settings: pihole-dns entries are set for ecovacs.com ecovacs.net ecouser.net; pinging them suceeds:
```
PS C:\Users\surface> ping ecovacs.com

Ping wird ausgeführt für ecovacs.com [192.168.3.96] mit 32 Bytes Daten:
Antwort von 192.168.3.96: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.3.96: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.3.96: Bytes=32 Zeit=3ms TTL=64
Antwort von 192.168.3.96: Bytes=32 Zeit=3ms TTL=64
```

3rd: seting up deebot4homeassistant with bumper fails in a timeout:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.deebot.config_flow
Source: custom_components/deebot/config_flow.py:82
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 14:11:45 (1 occurrences)
Last logged: 14:11:45

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/deebot/config_flow.py", line 82, in async_step_user
    self._devices = await _retrieve_devices(self.hass, data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deebot/config_flow.py", line 260, in _retrieve_devices
    devices = await api_client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/api_client.py", line 27, in get_devices
    credentials = await self._authenticator.authenticate()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 361, in authenticate
    self._credentials = await self._auth_client.login()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 106, in login
    login_password_resp = await self.__call_login_api(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 175, in __call_login_api
    return await self.__do_auth_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deebot_client/authentication.py", line 138, in __do_auth_response
    async with self._config.session.get(url, params=params, timeout=60) as res:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

Updating Homeassistant and Deebot4Homeassistant didnt changed the situation.

Perhaps you can give me a hint or check if its a problem caused by the addon.
Thanks

### On which deebot vacuum you have the issue?

Deebot T9

### Which version of the Deebot component are you using?

3.2.0

### Which version of Home Assistant are you using?

2024.1.6

### What type of installation are you running?

Home Assistant OS

### Country

de

### Instance type

Bumper

**Comment by edenhaus** [comment]
It can be a lot and there is probably a configuration issue on bumper or on your DNS redirects.
Please check if all of the DNS entries in https://bumper.readthedocs.io/en/latest/DNS_Setup/ are pointing to the your instance.

Also enable debug logs for this component and verify that all requests are pointing to your bumper instance. Probably you have forgotten one.

Please also note that the integration will try to connect via mqtt on the URL `mq-{continent}.useruser.net:433`
With HA 2024.2 this component was moved to the core and there you can override the URL (Meaning you override it with `192.168.3.96:8883`)
