### ISSUE TITLE
Error 500 during installation 

### ISSUE THREAD

**Issue by Giuserver** [DeebotUniverse/Deebot-4-Home-Assistant#521]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hi,
in HA container for docker, version 2023.11.2
i have this problem during installation for THE LAST VERSION 3.2.0.
<img width="553" alt="Screenshot 2024-02-04 alle 22 54 04" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/97843369/16316ac4-2383-4a69-a3c4-8733058e0836">

### On which deebot vacuum you have the issue?

DEEBOT 605

### Which version of the Deebot component are you using?

firmware 1.4.9 Android APP work great

### Which version of Home Assistant are you using?

2023.11.2

### What type of installation are you running?

Home Assistant Container

### Country

IT

### Continent

EU

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
2024-02-04 22:00:02.690 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 898, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1000, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2096, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2072, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 420, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 242, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 271, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for deebot not found: ['deebot-client==5.0.0'].
```

**Comment by edenhaus** [comment]
You have installed this custom component not via Hacs, which is the preferred way to do it. Otherwise, it would not be possible to install version `3.1.0 `or later as they require you to run at least HA `2024.1`.

Please use a version below `3.1.0` or upgrade your Home assistant

**Comment by Giuserver** [comment]
@edenhaus 
Yes, I do that. I can't install via HACS (moreover, i can't push Install button). 
First step: download package from here: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/3.1.0
Second step: unzip in custom_components/deebot
Third step: Add Integration via UI 
Work whit previous version like:
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/2.1.2

BUT DON'T work also with 3.1.0

I follow the advice: (Please upgrade to this version even if you are running older version of HA.) 
Reported here:
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/releases/3.2.0

By the way, i can't use the integration via 2.12 because i received error like:


2024-02-05 10:17:34.071 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getCleanInfo', 'payload': {'header': {'pri': '1', 'ts': 1707128239.024935, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}, response={'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2024-02-05 10:17:34.072 WARNING (MainThread) [deebot_client.commands.common] No response received for command "getCleanInfo". This can happen if the vacuum has network issues or does not support the command
2024-02-05 10:17:34.075 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getSpeed', 'payload': {'header': {'pri': '1', 'ts': 1707128254.074532, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}

2024-02-05 10:17:34.130 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PUBLISH (d0, q0, r0, m0), 'iot/p2p/getSpeed/HelperMQClientId-awseu-sts-ngiot-mqsjmq-3/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/kQIX/j', ...  (70 bytes)
2024-02-05 10:17:34.131 DEBUG (MainThread) [deebot_client.mqtt_client] Got message: topic=iot/p2p/getSpeed/HelperMQClientId-awseu-sts-ngiot-mqsjmq-3/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/kQIX/j, payload=b'{"header":{"pri":"1","ts":1707128254.074532,"tzm":480,"ver":"0.0.50"}}'
2024-02-05 10:17:34.131 DEBUG (MainThread) [deebot_client.mqtt_client] Command getSpeed does not support p2p handling (yet)

2024-02-05 10:17:34.268 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getBattery', 'payload': {'header': {'pri': '1', 'ts': 1707128239.219786, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}, response={'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}

2024-02-05 10:17:34.269 WARNING (MainThread) [deebot_client.commands.common] No response received for command "getBattery". This can happen if the vacuum has network issues or does not support the command
2024-02-05 10:17:34.269 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getCachedMapInfo', 'payload': {'header': {'pri': '1', 'ts': 1707128254.269589, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}
2024-02-05 10:17:34.277 DEBUG (MainThread) [deebot_client.authentication] Success calling api url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'getError', 'payload': {'header': {'pri': '1', 'ts': 1707128239.227473, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}, response={'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2024-02-05 10:17:34.277 WARNING (MainThread) [deebot_client.commands.common] No response received for command "getError". This can happen if the vacuum has network issues or does not support the command
2024-02-05 10:17:34.278 DEBUG (MainThread) [deebot_client.authentication] Calling api(1/3): url=https://portal-eu.ecouser.net/api/iot/devmanager.do, params={'mid': 'dl8fht', 'did': '464c6860-c594-480a-a3e4-50dc2f382979', 'td': 'q', 'u': 'dlfvxar3d2487a94', 'cv': '1.67.3', 't': 'a', 'av': '1.3.1'}, json={'cmdName': 'clean', 'payload': {'header': {'pri': '1', 'ts': 1707128254.278402, 'tzm': 480, 'ver': '0.0.50'}, 'body': {'data': {'act': 'start', 'type': 'auto'}}}, 'payloadType': 'j', 'td': 'q', 'toId': '464c6860-c594-480a-a3e4-50dc2f382979', 'toRes': 'np60', 'toType': 'dl8fht'}
2024-02-05 10:17:34.330 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PUBLISH (d0, q0, r0, m0), 'iot/p2p/getCachedMapInfo/HelperMQClientId-awseu-sts-ngiot-mqsjmq-53/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/gJ34/j', ...  (70 bytes)
2024-02-05 10:17:34.331 DEBUG (MainThread) [deebot_client.mqtt_client] Got message: topic=iot/p2p/getCachedMapInfo/HelperMQClientId-awseu-sts-ngiot-mqsjmq-53/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/gJ34/j, payload=b'{"header":{"pri":"1","ts":1707128254.269589,"tzm":480,"ver":"0.0.50"}}'
2024-02-05 10:17:34.331 DEBUG (MainThread) [deebot_client.mqtt_client] Command getCachedMapInfo does not support p2p handling (yet)
2024-02-05 10:17:34.345 DEBUG (MainThread) [deebot_client.mqtt_client.client] Received PUBLISH (d0, q0, r0, m0), 'iot/p2p/clean/HelperMQClientId-awseu-sts-ngiot-mqsjmq-59/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/dn49/j', ...  (116 bytes)
2024-02-05 10:17:34.346 DEBUG (MainThread) [deebot_client.mqtt_client] Got message: topic=iot/p2p/clean/HelperMQClientId-awseu-sts-ngiot-mqsjmq-59/ecosys/1234/464c6860-c594-480a-a3e4-50dc2f382979/dl8fht/np60/q/dn49/j, payload=b'{"header":{"pri":"1","ts":1707128254.278402,"tzm":480,"ver":"0.0.50"},"body":{"data":{"act":"start","type":"auto"}}}'
2024-02-05 10:17:34.347 DEBUG (MainThread) [deebot_client.mqtt_client] Command clean does not support p2p handling (yet)

**Comment by edenhaus** [comment]
I just saw it now. This integration does not support the Deebot 605
