### ISSUE TITLE
Unable to install in Home Assistant

### ISSUE THREAD

**Issue by emansih** [DeebotUniverse/Deebot-4-Home-Assistant#65]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Hi. I have added the integration via HACS
![image](https://user-images.githubusercontent.com/5896415/144829410-7113f0c3-b8fc-43e9-9bf1-d20539d7cc4a.png)

and restarted Home Assistant. When I go to Integration and attempt to add Deebot 4 Home Assistant. It's not found. When I try to add it via the widget in the docs(https://my.home-assistant.io/badges/config_flow_start.svg), the error is throw. 

```
Logger: homeassistant.config_entries
Source: config_entries.py:702
First occurred: 9:12:34 PM (2 occurrences)
Last logged: 9:17:45 PM

Cannot find integration deebot

```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:594
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:12:34 PM (4 occurrences)
Last logged: 9:17:45 PM

[1719888936] Error handling message: Unknown error
[1725744752] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 692, in websocket_get_translations
    resources = await async_get_translations(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 313, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 223, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 238, in _async_load
    for translation_strings in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 158, in async_get_component_strings
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 594, in _async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'deebot' not found.
``` 

### On which deebot vacuum you have the issue?

-

### Which version of the Deebot component are you using?

0.2.0

### Which version of Home Assistant are you using?

2021.11.5

### What type of installation are you running?

Home Assistant Container

### Country

AU

### Continent

AU

### Instance type

Cloud

**Comment by edenhaus** [comment]
Can you please verify that HACS has installed successfully the integration?
Can you verify that the folder `custom_components/deebot` is present (in the folder where your `configuration.yaml` is)?
Please provide also the information which addidtional custom components you have installed

**Comment by emansih** [comment]
It appears that HACS didn't successfully install the integration as I don't see the folder. Additional custom components installed 

1. alexa_media
2. hacs
3. nodered

It should be noted that the issue seems to appear in upstream too. 

https://github.com/And3rsL/Deebot-for-Home-Assistant/issues/246

**Comment by emansih** [comment]
From what I can tell, `__init__.py` needs to be filled but it is empty.

**Comment by edenhaus** [comment]
Please try to install it again via Hacs (menu -> reinstall) and verify that the files are installed correctly.

Or uninstall it completely, check that all files/folder is removed and after a restart install it again.

If the issue still exists, please open a issue directly on the hacs project.
